// I used AI for suggestions in this file but it was largely written by me except for the AI review routes which were generated by an AI agent.

// npm install express sqlite3 dotenv @google/genai
import express from 'express'
import sqlite3 from 'sqlite3'
import 'dotenv/config'
// Importing 
import { GoogleGenAI } from "@google/genai"

sqlite3.verbose()
const genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

const HTTP_PORT = 8000

var app = express()
app.use(express.json())

// Used this to prevent cors issues
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*')
    res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE')
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With,Content-Type, Accept')
    next()
})

app.use(express.static('public'))

// Connecting to the database
const resumedb = new sqlite3.Database('resume.db', (err) => {
    if (err) {
        console.error("Error opening database:", err.message)
    } else {
        console.log("Connected to resume.db")

        // Creating tblJobs
        const strQuery = "CREATE TABLE IF NOT EXISTS tblJobs (intJobID INTEGER PRIMARY KEY AUTOINCREMENT, strCompany TEXT, strTitle TEXT, strStartDate TEXT, strEndDate TEXT)"
        resumedb.run(strQuery, (err) => {
            if (err) {
                console.error("Error creating tblJobs:", err.message)
            } else {
                console.log("tblJobs created")
            }
        })

        // Creating tblResponsibilities
        const strResponsibilitiesQuery = "CREATE TABLE IF NOT EXISTS tblResponsibilities (intRespID INTEGER PRIMARY KEY AUTOINCREMENT, intJobID INTEGER, strDescription TEXT)"
        resumedb.run(strResponsibilitiesQuery, (err) => {
            if (err) {
                console.error("Error creating tblResponsibilities:", err.message)
            } else {
                console.log("tblResponsibilities created")
            }
        })

        // Creating tblSkills
        const strSkillsQuery = "CREATE TABLE IF NOT EXISTS tblSkills (intSkillID INTEGER PRIMARY KEY AUTOINCREMENT, strCategory TEXT, strSkillName TEXT)"
        resumedb.run(strSkillsQuery, (err) => {
            if (err) {
                console.error("Error creating tblSkills:", err.message)
            } else {
                console.log("tblSkills created")
            }
        })

        // Creating tblCertifications
        const strCertsQuery = "CREATE TABLE IF NOT EXISTS tblCertifications (intCertID INTEGER PRIMARY KEY AUTOINCREMENT, strName TEXT, strIssuer TEXT, strDateEarned TEXT)"
        resumedb.run(strCertsQuery, (err) => {
            if (err) {
                console.error("Error creating tblCertifications:", err.message)
            } else {
                console.log("tblCertifications created")
            }
        })

        // Creating tblAwards
        const strAwardsQuery = "CREATE TABLE IF NOT EXISTS tblAwards (intAwardID INTEGER PRIMARY KEY AUTOINCREMENT, strTitle TEXT, strDateReceived TEXT, strDescription TEXT)"
        resumedb.run(strAwardsQuery, (err) => {
            if (err) {
                console.error("Error creating tblAwards:", err.message)
            } else {
                console.log("tblAwards created")
            }
        })
    }
})



// Jobs Routes
app.get('/api/jobs', (req, res) => {
    const strQuery = "SELECT * FROM tblJobs"
    resumedb.all(strQuery, [], (err, rows) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: err.message })
        }
        else {
            res.status(200).json({ outcome: "success", message: rows })
        }
    })
})

app.post('/api/jobs', (req, res) => {
    const strCompany = req.body.strCompany
    const strTitle = req.body.strTitle
    const strStartDate = req.body.strStartDate
    const strEndDate = req.body.strEndDate

    // I would not normally name the columns in a query like this, but AI suggested that i add it so that we 
    // are adding the right rows to the right columns since we never actually pass in a ID.
    const strInsertQuery = "INSERT INTO tblJobs (strCompany, strTitle, strStartDate, strEndDate) VALUES (?,?,?,?)"
    resumedb.run(strInsertQuery, [strCompany, strTitle, strStartDate, strEndDate], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt save the job." })
        }
        else {
            res.status(201).json({ outcome: "success", message: "Job saved." })
        }
    })
})


app.delete('/api/jobs/:id', (req, res) => {
    const intJobID = req.params.id
    const strDeleteQuery = "DELETE FROM tblJobs WHERE intJobID=?"
    resumedb.run(strDeleteQuery, [intJobID], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt delete the job." })
        } else {
            res.status(200).json({ outcome: "success", message: "Job deleted." })
        }
    })
})

// Responsibilities Routes
app.get('/api/responsibilities', (req, res) => {
    const strQuery = "SELECT * FROM tblResponsibilities"
    resumedb.all(strQuery, [], (err, rows) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: err.message })
        }
        else {
            res.status(200).json({ outcome: "success", message: rows })
        }
    })
})

app.post('/api/responsibilities', (req, res) => {
    const intJobID = req.body.intJobID
    const strDescription = req.body.strDescription

    const strInsertQuery = "INSERT INTO tblResponsibilities (intJobID, strDescription) VALUES (?,?)"
    resumedb.run(strInsertQuery, [intJobID, strDescription], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt save the responsibility." })
        }
        else {
            res.status(201).json({ outcome: "success", message: "Responsibility saved." })
        }
    })
})


app.delete('/api/responsibilities/:id', (req, res) => {
    const intRespID = req.params.id
    const strDeleteQuery = "DELETE FROM tblResponsibilities WHERE intRespID=?"
    resumedb.run(strDeleteQuery, [intRespID], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt delete the responsibility." })
        } else {
            res.status(200).json({ outcome: "success", message: "Responsibility deleted." })
        }
    })
})

// Skills Routes
app.get('/api/skills', (req, res) => {
    const strQuery = "SELECT * FROM tblSkills"
    resumedb.all(strQuery, [], (err, rows) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: err.message })
        }
        else {
            res.status(200).json({ outcome: "success", message: rows })
        }
    })
})

app.post('/api/skills', (req, res) => {
    const strCategory = req.body.strCategory
    const strSkillName = req.body.strSkillName

    const strInsertQuery = "INSERT INTO tblSkills (strCategory, strSkillName) VALUES (?,?)"
    resumedb.run(strInsertQuery, [strCategory, strSkillName], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt save the skill." })
        }
        else {
            res.status(201).json({ outcome: "success", message: "Skill saved." })
        }
    })
})


app.delete('/api/skills/:id', (req, res) => {
    const intSkillID = req.params.id
    const strDeleteQuery = "DELETE FROM tblSkills WHERE intSkillID=?"
    resumedb.run(strDeleteQuery, [intSkillID], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt delete the skill." })
        } else {
            res.status(200).json({ outcome: "success", message: "Skill deleted." })
        }
    })
})

// Certifications Routes
app.get('/api/certifications', (req, res) => {
    const strQuery = "SELECT * FROM tblCertifications"
    resumedb.all(strQuery, [], (err, rows) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: err.message })
        }
        else {
            res.status(200).json({ outcome: "success", message: rows })
        }
    })
})

app.post('/api/certifications', (req, res) => {
    const strName = req.body.strName
    const strIssuer = req.body.strIssuer
    const strDateEarned = req.body.strDateEarned

    const strInsertQuery = "INSERT INTO tblCertifications (strName, strIssuer, strDateEarned) VALUES (?,?,?)"
    resumedb.run(strInsertQuery, [strName, strIssuer, strDateEarned], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt save the certification." })
        }
        else {
            res.status(201).json({ outcome: "success", message: "Certification saved." })
        }
    })
})


app.delete('/api/certifications/:id', (req, res) => {
    const intCertID = req.params.id
    const strDeleteQuery = "DELETE FROM tblCertifications WHERE intCertID=?"
    resumedb.run(strDeleteQuery, [intCertID], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt delete the certification." })
        } else {
            res.status(200).json({ outcome: "success", message: "Certification deleted." })
        }
    })
})


// Awards Routes
app.get('/api/awards', (req, res) => {
    const strQuery = "SELECT * FROM tblAwards"
    resumedb.all(strQuery, [], (err, rows) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: err.message })
        }
        else {
            res.status(200).json({ outcome: "success", message: rows })
        }
    })
})

app.post('/api/awards', (req, res) => {
    const strTitle = req.body.strTitle
    const strDateReceived = req.body.strDateReceived
    const strDescription = req.body.strDescription

    const strInsertQuery = "INSERT INTO tblAwards (strTitle, strDateReceived, strDescription) VALUES (?,?,?)"
    resumedb.run(strInsertQuery, [strTitle, strDateReceived, strDescription], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt save the award." })
        }
        else {
            res.status(201).json({ outcome: "success", message: "Award saved." })
        }
    })
})


app.delete('/api/awards/:id', (req, res) => {
    const intAwardID = req.params.id
    const strDeleteQuery = "DELETE FROM tblAwards WHERE intAwardID=?"
    resumedb.run(strDeleteQuery, [intAwardID], (err) => {
        if (err) {
            return res.status(500).json({ outcome: "error", message: "Couldnt delete the award." })
        } else {
            res.status(200).json({ outcome: "success", message: "Award deleted." })
        }
    })
})

// AI Review Route
app.post('/api/review', (req, res) => {
    const strDescription = req.body.strDescription

    if (!strDescription) {
        return res.status(400).json({ outcome: "error", message: "Missing description for review." })
    }

    // Calling the Google API to generate improved text based on the user's description
    genAI.models.generateContent({
        // Specifying which AI model to use.
        model: 'gemini-3-flash-preview',
        // The prompt we are passing to the AI to generate the text
        contents: "Rewrite the following text into a single, professional resume bullet point. Do not include any conversational text, explanations, formatting, or multiple options. Only return the final bullet point text. Text to improve: " + strDescription
    })
        .then(response => {
            // Once the AI generates the text, we send it back to the client
            res.status(200).json({ outcome: "success", message: response.text })
        })
        .catch(err => {
            // If the API call fails we log it and return an error
            console.error("AI Error:", err)
            res.status(500).json({ outcome: "error", message: "Failed to generate AI review." })
        })
})

app.listen(HTTP_PORT, () => {
    console.log('Listening on port', HTTP_PORT)
})